### ISSUE TITLE
请问下有编译好的exe释出吗？

### ISSUE THREAD

**Issue by Z-fly** [siren186/libewf4fool#1]
感谢♪(･ω･)ﾉ

**Comment by siren186** [comment]
用 visual studio 打开 [libewf4fool/libewf-official-release/msvscpp/libewf.sln](https://github.com/siren186/libewf4fool/blob/master/libewf-official-release/msvscpp/libewf.sln) 文件，编译下就能得到二进制文件了。

**Comment by Z-fly** [comment]
就是不想下这些环境才问的，，，所以能用Actions来编译吗？
